---
version: '3'

services:

  atmosphere:
    image: 'cyverse/atmosphere:release-v36-9'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - './logs/atmosphere:/opt/dev/atmosphere/logs'
      - './logs/celery:/var/log/celery'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    extra_hosts:
      - 'atmosphere:127.0.0.1'
      - 'postgres:127.0.0.1'
    network_mode: 'host'


  troposphere:
    image: 'cyverse/troposphere:release-v36-6'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - './logs/troposphere:/opt/dev/troposphere/logs'
    depends_on:
      - 'atmosphere'
    extra_hosts:
      - 'atmosphere:127.0.0.1'
      - 'postgres:127.0.0.1'
    network_mode: 'host'
